name: Maven build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      # Organization variables
      ESWITCH_ARTIFACTORY_USERNAME: ${{ vars.ESWITCH_ARTIFACTORY_USERNAME }}
      # Organization secrets
      ESWITCH_ARTIFACTORY_PASSWORD: ${{ secrets.ESWITCH_ARTIFACTORY_PASSWORD }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      # Repository secrets
      SIMPLEJAVAMAIL_SMTP_USERNAME: ${{ secrets.SIMPLEJAVAMAIL_SMTP_USERNAME }}
      SIMPLEJAVAMAIL_SMTP_PASSWORD: ${{ secrets.SIMPLEJAVAMAIL_SMTP_PASSWORD }}
      # Repository variables
      SIMPLEJAVAMAIL_SMTP_HOST: ${{ vars.SIMPLEJAVAMAIL_SMTP_HOST }}
      SIMPLEJAVAMAIL_IMAP_HOST: ${{ vars.SIMPLEJAVAMAIL_IMAP_HOST }}
      SIMPLEJAVAMAIL_DEFAULTS_FROM_ADDRESS: ${{ vars.SIMPLEJAVAMAIL_DEFAULTS_FROM_ADDRESS }}
      SIMPLEJAVAMAIL_DEFAULTS_TO_ADDRESS: ${{ vars.SIMPLEJAVAMAIL_DEFAULTS_TO_ADDRESS }}

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '24'
        distribution: 'zulu'
        cache: maven
    - name: set PROJECT_VERSION
      run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.4.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: env variables
      run: |
        echo ESWITCH_ARTIFACTORY_USERNAME: $ESWITCH_ARTIFACTORY_USERNAME
        echo PROJECT_VERSION: $PROJECT_VERSION
        echo run_number: ${{ github.run_number }}, run_attempt: ${{ github.run_attempt }}
    - name: Build with Maven
      run: mvn --no-transfer-progress -s settings.xml clean deploy
    - name: Commit snyk-result
      uses: EndBug/add-and-commit@v9
      with:
        author_name: e-switch Solutions Developer
        author_email: dev@e-switch.ch
        message: |
          snyk-result.json
          GitHub run #${{ github.run_number }}-${{ github.run_attempt }}
        add: 'snyk-result.json'
    - name: Commit README.md
      uses: EndBug/add-and-commit@v9
      with:
        author_name: e-switch Solutions Developer
        author_email: dev@e-switch.ch
        message: |
          README.md
          GitHub run #${{ github.run_number }}-${{ github.run_attempt }}
        add: 'README.md'

    - name: remove files from target
      run: |
        rm target/*-sources.jar

    - name: create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'target/*.jar'
        tag: 'v${{ env.PROJECT_VERSION }}'

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
